version: "3.7"

services:
  mynodered:
    image: nodered/node-red
    restart: unless-stopped
    user: root
    volumes:
      - ${PWD}/mqtt:/data
    ports:
      - 1880:1880
  mybroker:
    image: eclipse-mosquitto
    restart: unless-stopped
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
  kuksa-val:
    image: ghcr.io/eclipse/kuksa.val/kuksa-val:master
    restart: unless-stopped 
    ports:
      - 8090:8090
    environment:
      - LOG_LEVEL=ALL
      - KUKSAVAL_OPTARGS=--mqtt.publish=* --mqtt.topic-prefix=vss --mqtt.address=mybroker
    depends_on:
      - "mybroker"

